name: modrekt_who
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  email_validator: ^2.1.17
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: ^22.1.34
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/Modules.csv
  
